CREATE SEQUENCE EMPLOYEE_SEQ MINVALUE 1 START WITH 6 INCREMENT BY 1 CACHE 20 /
CREATE SEQUENCE STATUS_SEQ MINVALUE 1 START WITH 5 INCREMENT BY 1 CACHE 20 /
CREATE SEQUENCE COURSE_SEQ MINVALUE 1 START WITH 5 INCREMENT BY 1 CACHE 20 /
CREATE SEQUENCE CLASS_SEQ MINVALUE 1 START WITH 4 INCREMENT BY 1 CACHE 20 /
CREATE SEQUENCE EMPSCHEDULE_SEQ MINVALUE 1 START WITH 7 INCREMENT BY 1 CACHE 20 /
CREATE SEQUENCE LESSONTIME_SEQ MINVALUE 1 START WITH 25 INCREMENT BY 1 CACHE 20 /
CREATE SEQUENCE CHILD_SEQ MINVALUE 1 START WITH 9 INCREMENT BY 1 CACHE 20 /
CREATE SEQUENCE CHSCHEDULE_SEQ MINVALUE 1 START WITH 11 INCREMENT BY 1 CACHE 20 /

CREATE TABLE  "EMPLOYEE"
   (	"EMPLOYEEID" NUMBER NOT NULL ENABLE,
	"FULLNAME" VARCHAR2(100) NOT NULL ENABLE,
	"BIRTHDAY" DATE NOT NULL ENABLE,
	"TELEPHONE" VARCHAR2(13),
	"CITY" VARCHAR2(50) NOT NULL ENABLE,
	"MANAGER" NUMBER,
	"USERNAME" VARCHAR2(255),
	"PASSWORD" VARCHAR2(255),
	 CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPLOYEEID") ENABLE
   ) /

CREATE TABLE  "STATUS"
   (	"STATUSID" NUMBER,
	"NAME" VARCHAR2(50) NOT NULL ENABLE,
	"SALARY" FLOAT(126) NOT NULL ENABLE,
	 CONSTRAINT "STATUS_PK" PRIMARY KEY ("STATUSID") ENABLE
   ) /

CREATE TABLE  "COURSE"
   (	"COURSEID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(500),
	"DURATION" NUMBER NOT NULL ENABLE,
	"PRICE" FLOAT(126) NOT NULL ENABLE,
	 CONSTRAINT "COURSE_PK" PRIMARY KEY ("COURSEID") ENABLE
   ) /

CREATE TABLE  "CLASS"
   (	"CLASSID" NUMBER,
	"COURSEID" NUMBER,
	"NAME" VARCHAR2(100),
	"STARTDATE" DATE,
	 CONSTRAINT "CLASS_PK" PRIMARY KEY ("CLASSID") ENABLE
   ) /

ALTER TABLE  "CLASS" ADD CONSTRAINT "CLASS_FK" FOREIGN KEY ("COURSEID")
	  REFERENCES  "COURSE" ("COURSEID") ON DELETE SET NULL ENABLE /

CREATE TABLE  "EMPSCHEDULE"
   (	"EMPSCHEDULEID" NUMBER NOT NULL ENABLE,
	"EMPLOYEEID" NUMBER NOT NULL ENABLE,
	"STATUSID" NUMBER NOT NULL ENABLE,
	"CLASSID" NUMBER,
	 CONSTRAINT "EMPSCHEDULE_PK" PRIMARY KEY ("EMPSCHEDULEID") ENABLE
   ) /

ALTER TABLE  "EMPSCHEDULE" ADD CONSTRAINT "EMPSCHEDULE_FK2" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES  "EMPLOYEE" ("EMPLOYEEID") ON DELETE CASCADE ENABLE /
ALTER TABLE  "EMPSCHEDULE" ADD CONSTRAINT "EMPSCHEDULE_FK3" FOREIGN KEY ("STATUSID")
	  REFERENCES  "STATUS" ("STATUSID") ENABLE /
ALTER TABLE  "EMPSCHEDULE" ADD CONSTRAINT "EMPSCHEDULE_FK4" FOREIGN KEY ("CLASSID")
	  REFERENCES  "CLASS" ("CLASSID") ON DELETE CASCADE ENABLE /

CREATE TABLE  "LESSONTIME"
   (	"LESSONTIMEID" NUMBER NOT NULL ENABLE,
	"CLASSID" NUMBER NOT NULL ENABLE,
	"LESSONDATE" TIMESTAMP (6) NOT NULL ENABLE,
	 CONSTRAINT "LESSONTIME_PK" PRIMARY KEY ("LESSONTIMEID") ENABLE
   ) /

ALTER TABLE  "LESSONTIME" ADD CONSTRAINT "LESSONTIME_FK" FOREIGN KEY ("CLASSID")
	  REFERENCES  "CLASS" ("CLASSID") ON DELETE CASCADE ENABLE /

CREATE TABLE  "CHILD"
   (	"CHILDID" NUMBER NOT NULL ENABLE,
	"FULLNAME" VARCHAR2(100) NOT NULL ENABLE,
	"BIRTHDAY" DATE NOT NULL ENABLE,
	"CITY" VARCHAR2(50) NOT NULL ENABLE,
	"TELPARENT" VARCHAR2(13) NOT NULL ENABLE,
	 CONSTRAINT "CHILD_PK" PRIMARY KEY ("CHILDID") ENABLE
   ) /

CREATE TABLE  "CHSCHEDULE"
   (	"CHSCHEDULEID" NUMBER NOT NULL ENABLE,
	"CHILDID" NUMBER NOT NULL ENABLE,
	"CLASSID" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "CHSCHEDULE_PK" PRIMARY KEY ("CHSCHEDULEID") ENABLE
   ) /

ALTER TABLE  "CHSCHEDULE" ADD CONSTRAINT "CHSCHEDULE_FK" FOREIGN KEY ("CHILDID")
	  REFERENCES  "CHILD" ("CHILDID") ON DELETE CASCADE ENABLE /
ALTER TABLE  "CHSCHEDULE" ADD CONSTRAINT "CHSCHEDULE_FK3" FOREIGN KEY ("CLASSID")
	  REFERENCES  "CLASS" ("CLASSID") ON DELETE CASCADE ENABLE /
