package project.dao;

public class SqlConstants {
    public static final String GET_ALL_CHILDREN = "SELECT * FROM CHILD ORDER BY FULLNAME";
    public static final String ADD_CHILD = "INSERT INTO CHILD VALUES (CHILD_SEQ.NEXTVAL, ?, ?, ?, ?)";
    public static final String UPDATE_CHILD = "UPDATE CHILD SET FULLNAME=?, BIRTHDAY=?, CITY=?, TELPARENT=? WHERE CHILDID=?";
    public static final String CHILD_BY_ID = "SELECT * FROM CHILD WHERE CHILDID=?";
    public static final String DELETE_CHSCHEDULE = "DELETE FROM CHSCHEDULE WHERE CHILDID = ? AND CLASSID = ?";
    public static final String ADD_CHSCHEDULE = "INSERT INTO CHSCHEDULE VALUES (CHSCHEDULE_SEQ.NEXTVAL, ?, ?)";
    public static final String CHILDREN_BY_GROUP = "SELECT CHILD.CHILDID, CHILD.FULLNAME, " +
            "TRUNC(MONTHS_BETWEEN(SYSDATE, CHILD.BIRTHDAY)/12) AS AGE FROM CHILD, CHSCHEDULE SC, CLASS " +
            "WHERE SC.CLASSID=CLASS.CLASSID AND SC.CHILDID=CHILD.CHILDID AND CLASS.CLASSID=?";

    public static final String COURSE_BY_GROUP = "SELECT COURSE.* FROM COURSE, CLASS " +
            "WHERE CLASS.COURSEID=COURSE.COURSEID AND CLASS.CLASSID=?";
    public static final String GET_ALL_COURSES = "SELECT * FROM COURSE";
    public static final String ADD_COURSE = "INSERT INTO COURSE VALUES (COURSE_SEQ.NEXTVAL, ?, ?, ?, ?)";
    public static final String UPDATE_COURSE = "UPDATE COURSE SET NAME=?, " +
            "DESCRIPTION=?, DURATION=?, PRICE=? WHERE COURSEID=?";
    public static final String COURSE_BY_ID = "SELECT * FROM COURSE WHERE COURSEID=?";

    public static final String ID_OF_EMPLOYEE = "SELECT EMPLOYEEID FROM EMPLOYEE WHERE EMPLOYEE.USERNAME = ?";
    public static final String GET_ALL_EMPLOYEES = "SELECT EMP.EMPLOYEEID, EMP.FULLNAME ENAME, EMP.BIRTHDAY, " +
            "EMP.TELEPHONE, EMP.CITY, MNG.EMPLOYEEID MID, MNG.FULLNAME MNAME, EMP.USERNAME, EMP.PASSWORD " +
            "FROM EMPLOYEE EMP LEFT JOIN EMPLOYEE MNG ON EMP.MANAGER=MNG.EMPLOYEEID";
    public static final String ADD_EMPLOYEE = "INSERT INTO EMPLOYEE VALUES (EMPLOYEE_SEQ.NEXTVAL, ?, ?, ?, ?, ?, ?, ?)";
    public static final String EMPLOYEE_BY_ID = "SELECT EMP.EMPLOYEEID, EMP.FULLNAME ENAME, EMP.BIRTHDAY, " +
            "EMP.TELEPHONE, EMP.CITY, MNG.EMPLOYEEID MID, MNG.FULLNAME MNAME, EMP.USERNAME, EMP.PASSWORD " +
            "FROM EMPLOYEE EMP LEFT JOIN EMPLOYEE MNG ON EMP.MANAGER=MNG.EMPLOYEEID WHERE EMP.EMPLOYEEID=?";
    public static final String UPDATE_EMPLOYEE = "UPDATE EMPLOYEE SET FULLNAME=?, BIRTHDAY=?, TELEPHONE=?, " +
            "CITY=?, MANAGER=?, USERNAME=?, PASSWORD=? WHERE EMPLOYEEID=?";
    public static final String USER = "SELECT EMP.PASSWORD, STATUS.NAME FROM EMPLOYEE EMP, EMPSCHEDULE SC, STATUS " +
            "WHERE SC.EMPLOYEEID=EMP.EMPLOYEEID AND SC.STATUSID=STATUS.STATUSID AND EMP.USERNAME=?";
    public static final String GET_ALL_TEACHERS = "SELECT DISTINCT EMP.EMPLOYEEID, EMP.FULLNAME " +
            "FROM EMPLOYEE EMP, EMPSCHEDULE SC, STATUS WHERE EMP.EMPLOYEEID=SC.EMPLOYEEID " +
            "AND SC.STATUSID=STATUS.STATUSID AND STATUS.NAME IN ('ASSISTANT','PRO')";
    public static final String GET_STATUS_ID = "SELECT STATUSID FROM STATUS WHERE NAME=?";
    public static final String ADD_EMPSCHEDULE = "INSERT INTO EMPSCHEDULE VALUES (EMPSCHEDULE_SEQ.NEXTVAL, ?, ?, ?)";
    public static final String UPDATE_EMPSCHEDULE = "UPDATE EMPSCHEDULE SET EMPLOYEEID=? " +
            "WHERE CLASSID=? AND STATUSID=(SELECT STATUSID FROM STATUS WHERE NAME=?)";
    public static final String TEACHERS_BY_GROUP = "SELECT EMPSC.EMPSCHEDULEID, EMP.EMPLOYEEID, EMP.FULLNAME, STATUS.NAME " +
            "FROM CLASS, EMPSCHEDULE EMPSC, STATUS, EMPLOYEE EMP WHERE EMP.EMPLOYEEID=EMPSC.EMPLOYEEID " +
            "AND EMPSC.STATUSID=STATUS.STATUSID AND EMPSC.CLASSID=CLASS.CLASSID AND CLASS.CLASSID = ?";

    public static final String GET_ALL_GROUPS = "SELECT CLASS.CLASSID, CLASS.NAME, CLASS.STARTDATE, " +
            "COURSE.NAME COURSENAME, COURSE.COURSEID FROM CLASS LEFT JOIN COURSE ON CLASS.COURSEID=COURSE.COURSEID";
    public static final String ADD_GROUP = "INSERT INTO CLASS VALUES (CLASS_SEQ.NEXTVAL, ?, ?, ?)";
    public static final String GROUP_BY_NAME = "SELECT * FROM CLASS WHERE NAME=?";
    public static final String GROUP_NAME_BY_ID = "SELECT NAME FROM CLASS WHERE CLASSID=?";
    public static final String UPDATE_GROUP = "UPDATE CLASS SET COURSEID=?, NAME=?, STARTDATE=? WHERE CLASSID=?";
    public static final String LESSONS_BY_GROUP = "SELECT DATA.LESSONDATE FROM CLASS, LESSONTIME DATA " +
            "WHERE DATA.CLASSID=CLASS.CLASSID AND CLASS.CLASSID = ? ORDER BY DATA.LESSONDATE";
    public static final String ADD_LESSON = "INSERT INTO LESSONTIME VALUES (LESSONTIME_SEQ.NEXTVAL, ?, ?)";
    public static final String DELETE_LESSON = "DELETE FROM LESSONTIME WHERE CLASSID = ?";
    public static final String GET_SCHEDULE = "SELECT class.classid, class.name, lessontime.lessondate, status.name statusname " +
            "FROM lessontime, class, empschedule sc, employee em, status WHERE em.employeeid=sc.employeeid " +
            "AND sc.classid=class.classid AND lessontime.classid=class.classid AND sc.statusid=status.statusid " +
            "AND lessontime.lessondate BETWEEN TO_DATE (?, 'yyyy-mm-dd') AND TO_DATE (?, 'yyyy-mm-dd') " +
            "AND em.employeeid=? ORDER BY lessontime.lessondate";
}
